### ISSUE TITLE
Splat with named argument fails.

### ISSUE THREAD

**Issue by sfcgeorge** [egonSchiele/contracts.ruby#100]
Hi, I came across this years ago and a lecturer just reminded me of it. Finally I have a project that could benefit from Contracts. Really impressive work.

I've got some complex method signatures with splats, named arguments and doublesplats. I can't get Contracts to work for certain combinations and have distilled to a simple example:

```ruby
Contract Args[Num], { operation: Symbol } => Num
=> [[Contract, [#<Contracts::Args:0x007ffa24adfe78 @contract=Contracts::Num>, {{:operation=>Symbol}=>Contracts::Num}]]]
def nums(*nums, operation: :+)
  nums.inject(&operation)
end
=> :nums
nums(1,3,5,6)
ContractError: Contract violation for argument 2 of 4:
    Expected: {:operation=>Symbol},
    Actual: 3
    Value guarded in: Object::nums
    With Contract: Args, Hash => Num
```

Am I using Contracts wrong or is this a bug? 

A more complex signature from my actual project that hopefully fixing the above will solve:

```ruby
Contract Args[Or[Array, N]], { closed: Maybe[Bool] } => Path
def initialize(*nodes, closed: true, **options)
etc...
```

Thanks

**Comment by waterlink** [comment]
Thx for reporting @sfcgeorge. This looks like a bug. I think in current implementation `contracts.ruby` expect splat to be last argument (or the one before `&block`).

**Comment by sfcgeorge** [comment]
Ah thank you. This closed bug suggests this may be a regression. https://github.com/egonSchiele/contracts.ruby/issues/4

**Comment by waterlink** [comment]
Yes, it is a regression.

**Comment by sfcgeorge** [comment]
Ruby (MRI 2.1) isn't clear on parameter parsing semantics and even has some weird behaviour. What I've worked out so far:

I'm using the internal naming returned by `Method.parameters`, so:

* opt=optional positional argument
* req=required positional argument
* rest=splat positional argument array
* key=optional named argument
* keyreq=required named argument
* keyrest=doublesplat named argument hash
* block=block argument

What I've observed:

* opt args have to go before rest
* req args can go before or after rest
* opt args can't go before req args, except when the req is after rest (this is silly because it means the default value will never be used as there is a req argument later that must be filled, but Ruby does allow this!)
* key and keyreq args must be right before keyrest but either way round
* keyrest must come last or penultimate to a block
* block comes last

All valid examples:
```ruby
    def foo(a, b=2, *c, d); p [a,b,c,d]; end
    def foo(a=1, *b, c); p [a,b,c]; end
    def foo(a, b=2, *c, d, **e); p [a,b,c,d,e]; end
    def foo(a, b=2, *c, d, e:, **f); p [a,b,c,d,e,f]; end
    def foo(a, b=2, *c, d, e:, f:6, **g); p [a,b,c,d,e,f,g]; end
    # foo(1,2,3,:a,:b,4,e:5,f:6,g: :z) => [1, 2, [3, :a, :b], 4, 5, 6, {:g=>:z}]
    # foo(1,3,4,e:5) => [1, 3, [], 4, 5, 6, {}]
```

Contracts doesn't account for much of this behaviour. I think the issue is in `lib/contracts.rb` in th `call_with` method. I'll have a go at fixing it. My thoughts on how to do it to match what it seems Ruby does:

1) Starting backwards, validate the `block` if there is one then remove it from the args.
2) Validate the `keyrest` if there is one then remove it.
3) Loop from the back, validating `key`, `keyreq` and `req` until the `rest` is reached if there is one.
4) Loop from the front, validating `req` and `opt` until the `rest` is reached.
5) Continue looping, now validating any remaining args against `rest`.
