### ISSUE TITLE
Fail when defining a contract in a module without `include Contracts::Modules`

### ISSUE THREAD

**Issue by nixpulvis** [egonSchiele/contracts.ruby#103]
Despite being well documented, I still think it's bad behavior to allow contracts to be written on module functions without error, if they are going to be ignored. If someone writes a contract, it should be used.

```ruby
module Foo
  # include Contracts::Modules

  Contract Num => Pos
  def foo(x)
    bar - x
  end
end
```

This should fail, without the commented line.

**Comment by egonSchiele** [comment]
Makes sense to me.

**Comment by alex-fedorov** [comment]
Have you included the contracts globally? Because normally you shouldn't even have `Contract` method defined in this module

**Comment by nixpulvis** [comment]
Yea globally.

**Comment by alex-fedorov** [comment]
We actually want to deprecate this in 0.99 and forbid this in 1.0, because it creates real problems for different frameworks out there, when people just include contracts in global namespace. Usually it is way better to include it in target classes and modules, that actually need contracts, and not pollute `Object`

**Comment by nixpulvis** [comment]
Yea I read that after opening this issue. So maybe this won't be a problem, but it worries me that this can happen.

**Comment by egonSchiele** [comment]
Should be fixed, can you look @nixpulvis ?

**Comment by nixpulvis** [comment]
:+1: LGTM, however when global includes of `Contracts` are deprecated this can be safely removed. Which is the end game I guess.

**Comment by egonSchiele** [comment]
Yup!
