### ISSUE TITLE
to_s isn't called on contracts within Hash / Array

### ISSUE THREAD

**Issue by sfcgeorge** [egonSchiele/contracts.ruby#108]
Currently `inspect` is called on any Hash contracts and nothing more, so any nice custom `to_s` descriptions of the nested contracts aren't called. 

```ruby
{ binary: Or[1, 0] } 
# => Expected: {:binary=>#<Contracts::Or:0x007fc4639abee0 @vals=[1, 0]>}
```

I would like nicer Expected messages, so `to_s` to be called on each Class contract within any Hash contracts. Something like this:

```ruby
{ binary: Or[1, 0] }.map{ |k, v| [k, v.class==Class ? v.to_s : v] }.to_h
# => Expected: {:binary=>"1 or 0"}
```

It would also need to be recursive as there may be Hashes within Hashes, and the same improvement should probably be done for Array contracts too.

The current code is in `contracts.rb:114`:

```ruby
   expected = if data[:contract].to_s == "" || data[:contract].is_a?(Hash)
                data[:contract].inspect
              else
                data[:contract].to_s
              end
```

Perhaps by doing this it's unclear whether the string is a description or the actually expected string, e.g. in the example above is "1 or 0" telling us we need 1 or 0 or that we need the string "1 or 0". The above dummy solution doesn't work as it only works for class contracts—you want to call `to_s` on `Or[]` and such instance contracts but not on instances of primitives like 42 otherwise it will look like a string. I'm not sure if it's possible to solve these cleanly. Thoughts?

**Comment by sfcgeorge** [comment]
I think I have the answer to both problems.

Only call `to_s` on values who's class is `Class` or `CallableClass`, that way primitives like 42 won't be converted to a string but class contracts and instance contracts will be.

So that custom messages aren't confused with strings, use a different delimiter, I'm thinking backticks, round brackets or angle brackets. Backticks mean shell exec so that might be confusing and angle brackets could get confused for less that and get muddled with hashrocket syntax, so I suggest round brackets. 

First `inspect` the Hash to get a String as we currently do. Then recurse through the Hash checking each value is a contract as above, if it is then get the `to_s` representation, and `gsub` the value in the inspected Hash string wrapped in round brackets instead of quotes. An example of the result:

```ruby
{ binary: Or[1, 0] } 
# => Expected: {:binary=>(1 or 0)}
```

**Comment by waterlink** [comment]
I am afraid, that `gsub`bing will create lots of problems.. Probably it is better to have normal handling for `Hash` with iterating by keys and constructing string. Something like:

```ruby
class HashRepresentationWrapper
  def initalize(value)
    @value = value
  end

  def inspect
    @value
  end
end

def contract_representation(contract)
  return hash_contract_representation(contract) if Hash === contract
  contract.to_s
end

def hash_contract_representation(hash)
  hash.inject({}) { |repr, (k, v)|
    repr.merge(k => HashRepresentationWrapper.new(contract_representation(contract)))
  }
end
```

Naming is subject to challenging.

**Comment by sfcgeorge** [comment]
:O I did not realise inspect worked like that, very nice. Ok I see how this could quite elegantly solve the issue.

**Comment by sfcgeorge** [comment]
I'll try working on this as I have some time, unless you've already started. I'd probably call it `ContractInspectionWrapper` as it will be used for Arrays too.

**Comment by waterlink** [comment]
Thx! Feel free to do so, I haven't started this one yet. If you have any problems along the way, feel free to ask.
