### ISSUE TITLE
Add list of users to README?

### ISSUE THREAD

**Issue by alexanderdean** [egonSchiele/contracts.ruby#116]
I'd be very happy to give a testimonial about how awesome Contracts is. It literally saves us tons of pain each day.

**Comment by egonSchiele** [comment]
That would be great! Are you ok with me adding a testimonial like "Contracts literally saves us tons of pain each day -- Alexander Dean"?

**Comment by alexanderdean** [comment]
Yes sure - how about:

> Contracts literally saves us hours of pain at Snowplow every day

Alexander Dean

**Comment by alexanderdean** [comment]
"hours" or "tons", whatever you think best!

**Comment by egonSchiele** [comment]
Done. Thank you :)

**Comment by alexanderdean** [comment]
Thank you for contracts Aditya!
