### ISSUE TITLE
ArrayOf[ArrayOf[...]] not accepted

### ISSUE THREAD

**Issue by badal** [egonSchiele/contracts.ruby#119]
When using two levels array, like [[1;2], [3,4]], one can specify
       ArrayOf[Array]  # pass
but
       ArrayOf[ArrayOf[Num]]  # error
gives an error :

       ... yard-contracts/formatters.rb:260:in `eval': (eval):1: syntax error, unexpected $end, expecting ']'
       (SyntaxError)
         ArrayOf[ArrayOf[Num]
                           ^

**Comment by waterlink** [comment]
I assume you missed closing bracket `]`:

`ArrayOf[ArrayOf[Num]]` != `ArrayOf[ArrayOf[Num]`

**Comment by egonSchiele** [comment]
Actually, I wonder if it has to do with this eval in yard-contracts: https://github.com/sfcgeorge/yard-contracts/blob/master/lib/yard-contracts/formatters.rb#L260

Sounds like this is an issue with yard-contracts though, not contracts?

**Comment by badal** [comment]
@waterlink  : no, there was two closing brackets, the last one is not seen by eval
@egonSchiele : yes, it is an issue with eval in yard-contracts

I found a workaround :
Vector = ArrayOf[Num]   and then use  ArrayOf[Vector]
even Matrix = ArrayOf[Vector] and so on ...

**Comment by badal** [comment]
I reported to yard-contracts, issue #7.
So, closing, sorry for the noise.
