### ISSUE TITLE
Contracts on the instance of an object when contracting an instance method

### ISSUE THREAD

**Issue by NobbZ** [egonSchiele/contracts.ruby#121]
Hi there!

I would like to have a contract, that forbids to call the function `#foo` on an instance where attribute `bar` is set to `false`.

A condition for that could easily be implemented:
```rb
class UnBared
  def self.valid? val
    !val.bar
  end
end
```

But how can I use this in a contract, since the objectinstance is not an argument to the method.

**Comment by waterlink** [comment]
That actually looks like a feature, we may somehow pass it in as an
optional argument to valid?

**Comment by NobbZ** [comment]
I think you get me wrong here.

I don't even know where I should put that Contract. Lets look at this:

```rb
class Foo
  include Contracts

  Contract None => String # How can I tell contracts that this shall only work if current instance of Foo is a valid Unbared (defined in original post)
  def bar
    "this is an unbarred instance of Foo!"
  end
end
```

Without Contracts it would look something like this:
```rb
class Foo
  def bar
    if !self.bar then
      "this is an unbarred instance of Foo!"
    else
      raise "Nope! Not this way!"
    end
  end
end
```

**Comment by egonSchiele** [comment]
So if we pass in the instance of Foo to `valid?` you could write the same check inside the contract?

**Comment by NobbZ** [comment]
I can't imagine how that should look then.

I will try to write some proposal how I think it could be written as soon as I'm back at my PC.

**Comment by NobbZ** [comment]
OK, I'm back at my PC.

So what I think how we could do it, would be something like this:

```
class Foo
  include Contracts

  InstanceContract UnBared, None => String
  def bar
    "this is an unbarred instance of Foo!"
  end
end
```

Adding this additional decorator `InstanceContract` would make semantically clear, that this contract does depend on the current state of the instance. The first argument would be the contract which the current instance is tested against, then syntax is the same as with `Contract` decorator.

I would have done a PR, but I wasn't able to figure out how to write the mentioned decorator and where to put it.

**Comment by nixpulvis** [comment]
There are a few problems with this idea. Overall this kind of thing should be possible but we should avoid "hacking" it in.

- A new `InstanceContact` is confusing, and should ideally not be needed.
- A contract *currently* is essentially `Contract Type ... => Type ...`, but now we have something else. Looking into the proper way to bind contracts to functions even when the contracts are not based on function arguments.

**Comment by alex-fedorov** [comment]
We can handle it if we provide custom base class for contract. And if contract matches this custom base class we will pass in target of the contract (object instance). Idea is similar to `InstanceContract`, but to not pollute your interfaces:

```ruby
class UnBarred < Contracts::InstanceContract
  def valid?(instance)
    !instance.bar?
  end
end
```

And then you use `UnBarred` like this:

```ruby
class Foo
  include Contracts

  Contract UnBarred[None => String]
  def bar
    "this is unbarred instance of Foo!"
  end
end
```

**Comment by egonSchiele** [comment]
I'm leaning towards @nixpulvis on this. So far, contracts are for validating input and output to a function only. We make that assumption in a lot of places: like when we throw `ContractError`s), or use contracts as a type signature for methods. You are guaranteed that if a contract is failing, it is bad input or bad output.

If we allow contracts to access the instance, we don't have that guarantee anymore. It would be possible for a contract to fail, even if the user is passing in the correct parameters. I think that would get really confusing.

So I vote for contracts to be used for inputs/outputs only, and all other checks happen in the method itself, using `raise` etc. What do you think?

**Comment by alex-fedorov** [comment]
Agree, one may say, that such checks on the instance object should be part
of domain logic, not "assert on steroids".
