### ISSUE TITLE
Move `Testable` into it's own gem

### ISSUE THREAD

**Issue by nixpulvis** [egonSchiele/contracts.ruby#124]
I think keeping this codebase as clean, and clutter free is going to make working on the upcoming features much easier. `Testable` is a cool feature, but it solves a different problem than the main goal of `contracts`, so I feel it should be a separate gem.

**Comment by egonSchiele** [comment]
:+1:

**Comment by nixpulvis** [comment]
Along the same note, invariance could also be moved out too. But I wouldn't go that far. It's just a pretty separate code base.

**Comment by egonSchiele** [comment]
Done!
