### ISSUE TITLE
Please add CHANGELOG or mention changes on Releases

### ISSUE THREAD

**Issue by PikachuEXE** [egonSchiele/contracts.ruby#126]

**Comment by egonSchiele** [comment]
Yes, you are right. I need to be better about doing this.

**Comment by PikachuEXE** [comment]
I normally ask people to change CHANGELOG (+ README sometimes) in PR as last commit (once the changes are confirmed)
This saves a lot of work for me! :D
Yup I am proud of my laziness :DD

**Comment by egonSchiele** [comment]
Smart! In the meantime, are you worried about upgrading to the most recent version of contracts? I'll try to put a changelog together.

**Comment by PikachuEXE** [comment]
I am looking at the commits between 0.7 and 0.8 right now, before I commit the gem upgrade change

**Comment by egonSchiele** [comment]
Done!

**Comment by PikachuEXE** [comment]
Thx :D

**Comment by PikachuEXE** [comment]
Please add `0.10` CHANGELOG entries :)

**Comment by egonSchiele** [comment]
what would I do without you @PikachuEXE

**Comment by PikachuEXE** [comment]
And also I found #176 :S
