### ISSUE TITLE
Example of poor string representation

### ISSUE THREAD

**Issue by gsinclair** [egonSchiele/contracts.ruby#127]
Here is part of a contract violation message I got, regarding the return value:

    Expected: #<Contracts::Or:0x007f917c1a5fd0 @vals=[[false, nil, nil], [true, #<Contracts::ArrayOf:0x007f917c1a6070 @contract=#<Contracts::Or:0x007f917c19eaf0 @vals=[:move, :open, :rename, :delete]>>, [String]]]>,

The contract producing this was:

    Contract [String] => Or[ [false, nil, nil],
                             [true, ArrayOf[Action], [String]] ]

The "Action" is defined elsewhere:

    Action = Or[:move, :open, :rename, :delete]

Obviously the string representation of this contract could be improved.

**Comment by gsinclair** [comment]
Sorry, I had an error in my contract specification.  The "[String]" should have been "ArrayOf[String]".

Fixing that produced the string representation:

    Expected: [Bool, (Pathname or nil), ((an array of move, open, rename or delete) or nil)]

I find this representation a little curious -- it doesn't faithfully represent the contract that I typed -- but at least it's a lot better than what I reported above.

**Comment by gsinclair** [comment]
And once again I must apologise. The string representation in my second post came from a different contract entirely.

Best delete this issue report!

**Comment by egonSchiele** [comment]
closed.
