### ISSUE TITLE
Contracts for rails controllers

### ISSUE THREAD

**Issue by NobbZ** [egonSchiele/contracts.ruby#132]
Would it be possible to have the concept of contracts for a rails controller that does not check for arguments of a function but for the content of the `params`-hash?

I don't actually understand method decorators enough to try it by myself, but I would really like to use it.

**Comment by nixpulvis** [comment]
In a vanilla contract system you get pre and post callbacks essentially. This gem provides an interface to run pre and post conditions oriented around arguments and return values.

So it's not a stretch to think this could be done. It would just need a slightly differant interface.

**Comment by waterlink** [comment]
Make you `ActiveControllers` as thin as just delegating to your own `Controllers`, where you will pass in `params` as an argument to `initialize`, and put contract on `initialize`.

It is OO guy talks in me.

Rails guy in me will tell you that it sounds like a first feature for `contracts-rails` gem.

**Comment by egonSchiele** [comment]
I'm going to close this issue. Both of @waterlink's suggestions make sense to me.
