### ISSUE TITLE
Update documentation code for class invariant support

### ISSUE THREAD

**Issue by muhic** [egonSchiele/contracts.ruby#133]
Inside the `MyBirthday` class on the [documentation page](http://egonschiele.github.io/contracts.ruby/), the class invariant definition should invoke the correct method **`invariant`** instead of **`Invariant`**, else throws a `NoMethodError` . Here is the culprit:

```ruby
  Invariant(:day) { 1 <= day && day <= 31 }
  Invariant(:month) { 1 <= month && month <= 12 }
```

**Comment by waterlink** [comment]
It is already updated in `TUTORIAL.md` (ie source for documentation), but looks like documentation wasn't published.

/cc @egonSchiele

**Comment by egonSchiele** [comment]
Oops, done.
