### ISSUE TITLE
ArrayOf should not fail for empty arrays

### ISSUE THREAD

**Issue by sebnozzi** [egonSchiele/contracts.ruby#137]
I don't know if it's deliberate, but I do not expect an `ArrayOf[X]` contract to fail for an empty array.

In my understanding the contract has not been violated. It's not that the method returned an array of a _different_ type. It just was simply empty.

```ruby
Contract violation for return value:
        Expected: (a collection Array of MyClass),
        Actual: []
        Value guarded in: MyClass::fetch_xxx
        With Contract: None => CollectionOf
        At: ...
```

As I workaround, I have to resort to this:

```ruby
Contract None => Or[ArrayOf[MyClass], lambda{ |a| (a||[]).empty? }]
def fetch_xxx
  ...
end
```
which is not pretty.

**Comment by alex-fedorov** [comment]
You are right, it should accept `[]`.

There is a better workaround currently:

```ruby
Contract None => Or[[], ArrayOf[MyClass]]
```

**Comment by sebnozzi** [comment]
Still does not work for me:

```
Contract violation for return value:
        Expected: ((a collection Array of MyClass) or []),
        Actual: []
        Value guarded in: MyClass::fetch_xxx
        With Contract: None => Or
        At: ...
```

But this is because the `[ ]` being returned is a string representation of an empty `ActiveRecord::Relation`. Even if this holds true for that return value:

```ruby
(rdb:1) result
[]
(rdb:1) result.class
ActiveRecord::Relation
(rdb:1) result == []
true
(rdb:1) result.empty?
true
```
It seems that Contracts generally don't work with `ActiveRecord::Relation` instances. For example:

```ruby
class Bar < ActiveRecord::Base

  has_many :foos
  
  Contract String => ArrayOf[Foo]
  def foos_with_email(e)
    foos.where(:email => e)
  end

end
```

This always violates the contract. No matter if empty or not.

Is this known? Should I create a separate issue for it? 

Would it be an acceptable enhancement?
Or is it out of scope for the project?

**Comment by alex-fedorov** [comment]
Ah, this is active_record..

Then this violation is correct, because `ActiveRecord::Relation` is clearly not an `Array`.

And if you want to make it properly, you need custom contract:

```ruby
Contract String => ActiveRecord::RelationOf[Foo]
```

where `RelationOf` is:

```ruby
module ActiveRecord
  class RelationOf < Contracts::CallableClass
    def intiialize(item_contract)
      @item_contract = item_contract
    end

    def valid?(relation)
      return false unless relation.is_a?(Relation)
      relation.all? { |item| Contract.valid?(item, item_contract) }
    end

    private
    attr_reader :item_contract
  end
end
```

And if you are on the master branch of `contracts` you can use `CollectionOf` contract (it is private contract currently):

```ruby
ActiveRecord::RelationOf = Contracts::CollectionOf::Factory.new(ActiveRecord::Relation)
```

**Comment by alex-fedorov** [comment]
And this is really sounds like something like `contracts-rails` gem is needed, for example look here: https://github.com/egonSchiele/contracts.ruby/issues/132

**Comment by egonSchiele** [comment]
+1 for putting this in `contracts-rails`. The contract passes as expected for an empty array. Test code:

```ruby
Contract nil => ArrayOf[Num]
def arr
  []
end
```

**Comment by sebnozzi** [comment]
But... just to be clear... there is no such thing as `contract-rails` yet, right?

@egonSchiele I was betting on the possibility to adapt the implementation of ArrayOf in such a duck-typing way that it works both for real `Array` instances and for things behaving like them... (in an ActiveRecord-agnostic way, of course)

Otherwise, thanks for your pointer for the custom contract.

**Comment by waterlink** [comment]
There is no such thing as `contract-rails` yet. You can create it if you feel like. If nobody creates it and we will have more of this rails-related issues, I will probably create one soon.

In the master you could do:

```ruby
DuckCollectionOf = Contracts::CollectionOf::Factory.new(RespondTo[:each, :map, ...])
```

**Comment by alex-fedorov** [comment]
@sebnozzi BTW, in `contracts 0.9` builtin `Contracts::CollectionOf::Factory` should be available. So you can create your own collection contracts almost at no cost.

**Comment by sebnozzi** [comment]
@alex-fedorov That's great! Thanks for the pointer.

**Comment by betamatt** [comment]
FYI, I had implemented `RelationOf` as `RelationOf[ModelClass]`
```
module Contracts
  class RelationOf < CallableClass
    def initialize(klass)
      @klass = klass
    end

    def valid?(val)
      ActiveRecord::Relation === val && @klass == val.klass
    end

    def to_s
      "an ActiveRecord::Relation on #{@klass.name}"
    end
  end
end
```

Trying to allow for `RelationOf[SomeOtherContract]` is dangerous since it's going to prematurely resolve the relation. I didn't feel the flexibility was worth the risk.

**Comment by alex-fedorov** [comment]
This can be solved with very interesting trick. Lazy contracts. They will
be checked only when relation will be resolved. But that means wrapping the
relation before actually passing it in method, and this requires changes to
contracts core code. See how Func contract is handled - something along
this lines.

**Comment by alex-fedorov** [comment]
I assume, that this can be closed? Continue conversation here, if you want it to stay open.
