### ISSUE TITLE
Decorator implementation conflicts with Draper

### ISSUE THREAD

**Issue by betamatt** [egonSchiele/contracts.ruby#138]
Both implementations define `decorate`. 

It seems that Contract's decorators are intended only for internal consumption and could be hidden away. One strategy is to have a single "engine" variable which is composed onto a class. The engine contains all data and methods required by Contracts and effectively provides a namespace, preventing any instance variables and methods from conflicting with those defined by the class. All functionality is accessed through the engine instance which contains a reference to the owning class such that `object.decorate` becomes `object.contracts.decorate`.

**Comment by waterlink** [comment]
Yes, you are right. We should somehow hide it. Not sure about engine object approach now, but might use that as well.

**Comment by waterlink** [comment]
Additionally we have `.fetch_decorators`, `.pop_decorators` and `common_method_added`, these should be probably hidden too.

**Comment by waterlink** [comment]
And we add `.owner_class` for eigenclasses (singleton classes)

**Comment by waterlink** [comment]
@betamatt can you try this branch from my fork: https://github.com/waterlink/contracts.ruby/tree/non_intrusive_method_decorators if it works for you?

It is still pretty dirty hack, so I don't create a PR yet, I will need to clean it up later.

**Comment by betamatt** [comment]
Examined. The code appears to be the general solution I described. I tested it on my app and it appears to preserve contract behavior while preventing collision with gems such a Draper. :+1:

Thanks so much.

**Comment by alex-fedorov** [comment]
I will clean it up today in the evening and hopefully create a PR
