### ISSUE TITLE
Combining Args and Optional Proc fails

### ISSUE THREAD

**Issue by tdreyno** [egonSchiele/contracts.ruby#139]
Example, which is the signature Rack uses for middleware:

```
Contract Any, Args[Any], Maybe[Proc] => Any
def use(middleware, *args, &block)
  @middleware << MiddlewareDescriptor.new(middleware, args, block)
end
```

In 0.9, the Args assumes the last value is either Proc or nil. But when no proc is passed, the last arg should be a part of the `*args`. Perhaps `Maybe` is not right for something so weirdly Ruby as the optional block usage.

In code:

```
use ::Rack::Static, path: "/"
```

or

```
use ::MinifyCSS do |m|
  m.compressor = :yahoo
end
```

**Comment by egonSchiele** [comment]
@sfcgeorge would be willing to take a look at this? You know that code better than me now.

**Comment by sfcgeorge** [comment]
Ok I see the issue, odd as I thought there were tests for blocks but I guess not this case. I have some time to look at this now.

**Comment by egonSchiele** [comment]
@tdreyno could you see if master works for you?

**Comment by tdreyno** [comment]
I think so, but now something else broke. Maybe it's related. Or, also, I'm bad at this :)

```

      IGNORE_DESCRIPTOR = Or[Regexp, RespondTo[:call], String]
      OPTIONS_DESCRIPTOR = {
        middleman_app: IsA['Middleman::Application'],
        id: Maybe[Symbol],
        proc: Or[Proc, Method],
        url_extensions: ArrayOf[String],
        source_extensions: ArrayOf[String],
        ignore: ArrayOf[IGNORE_DESCRIPTOR]
      }

      Contract RespondTo[:call], OPTIONS_DESCRIPTOR => Any
      def initialize(app, options={})
```

**Comment by sfcgeorge** [comment]
Oh my that's a handful. If there's something wrong with that it wouldn't be with the fix I just pushed as that was specifically for `Maybe[Proc]` being the last argument. So probably open a new issue please :)

**Comment by egonSchiele** [comment]
What error does that throw?

**Comment by tdreyno** [comment]
```
Contract violation for argument 3 of 4: (ParamContractError)
        Expected: nil,
        Actual: nil
        Value guarded in: Middleman::Middleware::InlineURLRewriter::initialize
        With Contract: RespondTo, Hash => Any
```

**Comment by tdreyno** [comment]
@sfcgeorge Refactoring a very configurable, duck-typed to hell API into Contracts means you get some nasty type signatures. But it's great, because it's very clear exactly how confusing the initial API may have been

**Comment by sfcgeorge** [comment]
@tdreyno Mmm yeah I bet Contracts could simplify the implementation a lot for that case, also serving as a form of documentation really. Hopefully we can get it fixed, Expected: nil, Actual: nil looks really odd.

**Comment by sfcgeorge** [comment]
@tdreyno Nope can't reproduce. Here's the code I used and no errors:

```ruby
Contract RespondTo[:call], {
  middleman_app: String,
  id: Maybe[Symbol],
  proc: Or[Proc, Method],
  url_extensions: ArrayOf[String],
  source_extensions: ArrayOf[String],
  ignore: ArrayOf[Or[Regexp, RespondTo[:call], String]]
} => Any
def crazy_hash(app, options = {})
end

crazy_hash(proc {}, middleman_app: "application",
                    id: :an_id,
                    proc: proc {},
                    url_extensions: ["org", "com"],
                    source_extensions: ["rb", "js"],
                    ignore: ["foo", /bar/])
```

I just inlined the hash and changed `Middleman::Application` to `String` so I didn't have to create a dummy class. Also, `IsA` isn't a contract, is that a custom contract you've defined or something? So I removed that.

As it works fine for me you'll have to open an issue with a simplified and reproducible test case please.

**Comment by tdreyno** [comment]
@sfcgeorge I think it may be triggered by either missing a required param or adding an unknown one.
