### ISSUE TITLE
Integration with rspec/mocking

### ISSUE THREAD

**Issue by mcandre** [egonSchiele/contracts.ruby#14]
I'm not sure how contracts should integrate with rspec tests and mocking, especially stubbed things and weird testing calls where you try to send `nil` to a method that expects a `String`. Sometimes when I insert a contract, the rspec tests break, and I'm not sure whether this means I've discovered a new edge case, or whether Contracts is simply being incompatible with rspec.

For now, I'm treating rspec tests as sacrosanct and omitting contracts for some of my methods (e.g. initializers #11).

**Comment by waterlink** [comment]
To me this sounds like a topic for creating so called plugin gem, `contracts-rspec`, because I'm pretty sure the same (or similar) problem happens with other mocking frameworks and including knowledge how to deal with them in one gem is too much.

WDYT @egonSchiele, @mcandre ?

**Comment by mcandre** [comment]
Any solution is better than no solution I suppose

**Comment by egonSchiele** [comment]
I agree, seems like this would add a lot of rspec-specific code to this gem.

**Comment by alex-fedorov** [comment]
Got it running: https://github.com/waterlink/contracts-rspec You might be able to use now `instance_double(YourClassNameHere)` and it will pass contract `YourClassNameHere`.

**Comment by egonSchiele** [comment]
Can I close this issue @waterlink @mcandre ? Is the contracts-rspec solution satisfactory?

**Comment by alex-fedorov** [comment]
And now we have 2 solutions: contracts-rspec and override_validator(:class)

So we should be safe to close this issue.
