### ISSUE TITLE
Hash ordering in Contracts

### ISSUE THREAD

**Issue by jdickey** [egonSchiele/contracts.ruby#144]
I have a class that looks something like this:

```ruby
class Show
  include Contracts

  attr_reader :entity

  INIT_CONTRACT_INPUTS = {
    target_slug: String,
    current_user: UserDao,
    repository: RespondTo[:find_by_slug]
  }

  Contract INIT_CONTRACT_INPUTS => Show
  def initialize(target_slug:, current_user:, repository:)
    @target_slug = target_slug
    @current_user = current_user
    @repository = repository
    self
  end
  # ...
end
```

The contract works just fine, with one hiccup. One of the features of a Hash is that it doesn't matter what order you supply the keys in, as Ruby 2.0+ will order them alphabetically by key anyway. Yet any variation in ordering is presently a Contract violation. IMO this should not be, or should at least be configurable.

**Comment by waterlink** [comment]
Can you provide how you use this code? I can't reproduce..

**Comment by jdickey** [comment]
I'll try and boil down a simplest-possible-failure case in the next couple-three days; sorry for not catching this until the wrong end of the weekend.

**Comment by jdickey** [comment]
I'm going to go ahead and close this; I've been distracted onto other things and, though I've run into that once or twice since opening this issue, the workaround is simple enough that boiling down a simplest-possible test case is going to take more time than I can presently justify. Sorry.

**Comment by egonSchiele** [comment]
Ok thanks for reporting anyway. Lets see if anyone else runs into this issue...
