### ISSUE TITLE
Contract on method initialize raises NameError

### ISSUE THREAD

**Issue by Burdette-at-R1Soft** [egonSchiele/contracts.ruby#146]
I've found everything I need in the gem, with one exception:  I have not been able to put a contract onto an initialize method.

Is that expected?

Here's some irb:

C:\Users\Burdette.Lamar>irb
irb(main):001:0> require 'contracts'
=> true
irb(main):002:0> class Foo
irb(main):003:1> include Contracts
irb(main):004:1> Contract None => nil
irb(main):005:1> def initialize
irb(main):006:2> end
irb(main):007:1> end
NameError: undefined method `Foo' for class `Foo'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/contracts-0.6/lib/contracts/method_reference.rb:27:in `private'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/contracts-0.6/lib/contracts/method_reference.rb:27:in `block in make_private'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/contracts-0.6/lib/contracts/method_reference.rb:27:in `class_eval'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/contracts-0.6/lib/contracts/method_reference.rb:27:in `make_private'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/contracts-0.6/lib/contracts/decorators.rb:174:in `common_method_added'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/contracts-0.6/lib/contracts/decorators.rb:33:in `method_added'
        from (irb):5:in `<class:Foo>'
        from (irb):2
        from C:/Ruby193/bin/irb:12:in `<main>'
irb(main):008:0>

**Comment by waterlink** [comment]
You are using contracts `0.6` (I think it was broken) have you tried it on latest version (ie: `0.9`)

**Comment by Burdette-at-R1Soft** [comment]
Upgrade to  v0.9 fixes my irb example.  Will apply to real code and squawk if problems.
