### ISSUE TITLE
Expanded array in remaining-argument list?

### ISSUE THREAD

**Issue by jdickey** [egonSchiele/contracts.ruby#149]
Given a (Rails vew-helper) method

```ruby
  def sort_by_timestamp(post, *fields)
    selectors = post.attributes.to_hash.select { |k, _v| fields.include? k }
    return Time.zone.now if selectors.empty?
    selectors.first
  end
```

How would you specify a contract for that when, instead of calling with an explicit array of symbols (which would let me use `ArrayOf[Symbol]`), you'd have calls with different sequences, like `sort_by_timestamp post, :pubdate` vs `sort_by_timestamp post, :upcated_at, :created_at`, and so forth?

Or do you take the position that "you really ought to force the parameters *at call time* into an explicit array"?

**Comment by alex-fedorov** [comment]
`Contract Symbol, Args[Symbol]` if I understood the question. This is in
the tutorial.

**Comment by jdickey** [comment]
*d'oh!* Sorry; glossed right over it.

I have *got* to stop these more-working-than-not 24-hour cycles. Thanks again.

**Comment by egonSchiele** [comment]
Cool! Closing this issue.
