### ISSUE TITLE
Modules as contracts are recognised as value contract instead of class contract

### ISSUE THREAD

**Issue by waterlink** [egonSchiele/contracts.ruby#152]
Given:

```ruby
module M; end

class X
  include M
end

Contract M => nil
def hello(x)
end
```

Expected:

```ruby
hello(X.new)     # => nil
```

Actual:

```
ParamContractError: Contract violation for argument 1 of 1:
        Expected: M,
        Actual: #<X:0x00000102a2df98>
        Value guarded in: Object::hello
        With Contract: Module => NilClass
        At: (irb):10
```

Relevant code: https://github.com/egonSchiele/contracts.ruby/blob/master/lib/contracts.rb#L252-L253

Condition should be `klass == Class || klass == Module`.

Why? - module inclusion is valid way to do inheritance, so I want to check if something is enumerable or comparable (and much more stuff I do :) ) for example.

**Comment by egonSchiele** [comment]
nice catch!
