### ISSUE TITLE
Errr: "uninitialized constant" for classes not yet loaded

### ISSUE THREAD

**Issue by mcandre** [egonSchiele/contracts.ruby#16]
I'm trying to use contracts.ruby in my Ruby gem. I `require "contracts"` and `include Contracts` in a global script, then `require` my local scripts one by one.

When writing methods, I often need to reference a class defined in a different Ruby file. My methods are functioning properly, but when I try to write a contract that references a class that hasn't loaded yet, contracts.ruby gets confused, reporting an error `uninitialized constant`.

As a mitigation, I can sometimes alter the `require` order in my global libs script. But when multiple classes depend on each other, no order will solve this issue.

**Comment by andy-twosticks** [comment]
I get this too.  Commenting out the contract line solves the issue, so this is clearly NOT a ruby thing.
