### ISSUE TITLE
Support for pzol/deterministic

### ISSUE THREAD

**Issue by alem0lars** [egonSchiele/contracts.ruby#160]
At the moment [egonSchiele/contracts.ruby](https://github.com/egonSchiele/contracts.ruby) uses `Monad` which overlaps with the monad definition in [pzol/deterministic](https://github.com/pzol/deterministic).

I'd like to use both the gems ofc..

Is it possible to prevent name clashing?

**Comment by nixpulvis** [comment]
See #157

**Comment by alex-fedorov** [comment]
It doesn't have `Monad`.

**Comment by alex-fedorov** [comment]
@alem0lars maybe you are using this: https://github.com/beezee/kleisli-contracts ?

**Comment by alem0lars** [comment]
Ah lol... I'd like to say `Maybe` but in my head was thinking it's a monads so I wrote Monads... Ahahah

**Comment by alem0lars** [comment]
Does anyone know how to prevent nameclash?

**Comment by waterlink** [comment]
@alem0lars I think #157 is a blocker from such nameclashes.. So we need to find a proper solution for it first. Any ideas?

**Comment by alem0lars** [comment]
@waterlink The long term and more elegant solution is writing our own parser to really have a DSL. This also prevents any namespace pollution cuz just Contract (and some other small stuff) has to be available.
The gem `treetop` (also used by `rails` if I remind correctly) will semplify the work a lot.
----
Since now, I think it's better to continue discussion in #157

**Comment by egonSchiele** [comment]
Closing this issue since #157 has a long discussion about the same issue.
