### ISSUE TITLE
Allow use of contracts in the middle of a method

### ISSUE THREAD

**Issue by gsinclair** [egonSchiele/contracts.ruby#164]
I have a method that receives a hash as its argument. The contents of the hash must follow a certain contract, but it's too complex to specify outside the method. It would be nice to have code like

    Contracts.assert args[:DEFAULT] => HashOf[Symbol, Any]

That would be less code than I need to write at the moment. And it would give an appropriate error message too.

**Comment by waterlink** [comment]
Sounds like your method is too big and does too much. Solution: extract
private methods out of it. WDYT?

**Comment by gsinclair** [comment]
I agree in general, but there are times when _something_ has to process a varied bunch of data. That method will farm bits and pieces out to other methods, but for the sake of a convenient API, one method has to be the starting point.

If the API only has one public method, then I feel it's responsible for detecting contract errors, even if it's complicated.

That said, your comment is causing me to consider an alternative.

**Comment by waterlink** [comment]
Extracting couple of private methods will not change public interface. If
it is too much of them - extract private class.

**Comment by gsinclair** [comment]
If the public interface (a single method) takes in a lot of data (with a complex structure) and then gets various private methods to do the work on bits of that data, then you still have the situation where the public interface needs a contract that may be more complicated than one would like.

I _did_ change my interface to have more than one method, and this reduced the need for programmatic access to contract validation considerably, but there are still a couple of places in my code where I have used

    Contract.valid?(value, specification)

to good effect.

**Comment by waterlink** [comment]
If you need such a broad public interface, then there is high chance that
there is violation of SRP (Single Responsibility Principle). And yes, you
can use `Contract.valid?` for your own usage, but currently this is not
documented. Do you want to make a PR to `TUTORIAL.md` and add section with
some minimal example when this can be useful?

--
Best Regards,
Alexey Fedorov,
Sr Ruby Developer, Clojure Developer, Rust Developer,
+49 15757 486 476

2015-06-27 13:47 GMT+03:00 Gavin Sinclair <notifications@github.com>:

**Comment by gsinclair** [comment]
Done. Pull request submitted.

**Comment by egonSchiele** [comment]
Merged your PR.
