### ISSUE TITLE
Add range as a contract

### ISSUE THREAD

**Issue by egonSchiele** [egonSchiele/contracts.ruby#167]
To say that this function expects a number between 1 - 10. Options:

```ruby
Contract (1..10) => Bool
```

OR

```ruby
Contract InRange[1..10] => Bool
```

We might have to reserve `1..10` (from the first example) so people can write contracts for functions that expect a range as an argument. In which case we would implement the second solution.

**Comment by gsinclair** [comment]
I vote for the first option. We already have a disconnect between what is literally specified and what is meant.  When I specify `Contract String => Any` does my method take _a_ string or does it take _the object_ String (that is to say, a class object)? Of course, it takes _a_ string.

If I wanted to do method overloading based on a class object that was provided? I'm out of luck.

```ruby
Contract String => Any
def foo(klass) ... end

Contract Array => Any
def foo(klass) ... end

Contract Hash => Any
def foo(klass) ... end
```

Those specifications will not honour my intention that a class object be provided to the method.

So with a range?  Someone expecting _a_ range to be provided can of course do `Contract Range => Any`.

Within the context of the contracts.ruby project, the most obvious and useful meaning of `Contract (1..10) => Any` is that the argument provided will satisfy `(1..10).include? val`.

This is even more so when you consider case equality:
```ruby
case object
when String then ...
when /pattern/ then ...
when (1..10) then ...
end
```

**Comment by egonSchiele** [comment]
Fair enough, `Contract (1..10) => Bool` looks nicer to me too.
