### ISSUE TITLE
Allow for literal specification of values in contracts

### ISSUE THREAD

**Issue by gsinclair** [egonSchiele/contracts.ruby#168]
The contract `String => Any` requires the argument to be _a string object_.

The contract `5 => Any` requires the argument to be _the actual value 5_.

So how do I specify that the argument should be _the actual value String_? This is how it could be specified: `Literally[String] => Any`.

**Comment by waterlink** [comment]
@gsinclair Hi, thanks for opening this issue. This sounds like a valid builtin contract. Are you up to making a PR ?

**Comment by egonSchiele** [comment]
You should be able to use the `Eq` class for this.

**Comment by waterlink** [comment]
I see, I forget about it. And apparently it is not documented in `TUTORIAL.md` here: https://github.com/egonSchiele/contracts.ruby/blob/master/TUTORIAL.md#built-in-contracts

**Comment by gsinclair** [comment]
Heh... Eq is a much better name, too. I'll do a PR with the documentation.

**Comment by jeremyf** [comment]
@gsinclair Can this issue be closed?

**Comment by gsinclair** [comment]
Yes. I didn't realise it was for me to do so. Closing.
