### ISSUE TITLE
RangeOf[type]

### ISSUE THREAD

**Issue by gsinclair** [egonSchiele/contracts.ruby#169]
One of my methods takes a date range as an argument. I have written a `RangeOf` callable class so I can specify it as `RangeOf[Date]`. This would be a nice addition to Contracts, complementing `ArrayOf` and `HashOf`.

(`SetOf` would be nice, too, but that's a separate matter.)

**Comment by alex-fedorov** [comment]
We already have `SetOf`: https://github.com/egonSchiele/contracts.ruby/blob/master/lib/contracts/builtin_contracts.rb#L286-L290

Sounds like a good addition to me :)

**Comment by gsinclair** [comment]
Hah! I wasn't aware.

`SetOf` is included in `TUTORIAL.md` but that version of the tutorial is not what's visible at http://egonschiele.github.io/contracts.ruby

I guess it's a recent addition.

**Comment by gsinclair** [comment]
RangeOf is implemented in pull request #171.

**Comment by egonSchiele** [comment]
merged.
