### ISSUE TITLE
Release 1.0?

### ISSUE THREAD

**Issue by adarsh** [egonSchiele/contracts.ruby#175]
Hey! I love this gem, but I'm bundling master to get the `KeywordArgs` feature.

Any release planned with these new features?

**Comment by waterlink** [comment]
Hi @adarsh. We can do a release, but next release will not be `0.10`, not `1.0` ;) We still want to change some stuff before `1.0.0` (see: #157 and #87)

/cc @egonSchiele WDYT, are we good to release `0.10` ?

**Comment by egonSchiele** [comment]
yup! I'll release shortly

**Comment by egonSchiele** [comment]
pushed version `0.10`.

**Comment by adarsh** [comment]
Thanks!



-- 
@adarshp <http://www.twitter.com/adarshp>
313.454.1515 (mobile)
See when I am free: http://bit.ly/adarshcal
