### ISSUE TITLE
If defined? better here?

### ISSUE THREAD

**Issue by dg-ratiodata** [egonSchiele/contracts.ruby#178]
Hi would you mind to check if the variable is defined here? https://github.com/egonSchiele/contracts.ruby/blob/master/lib/contracts.rb#L254

```ruby
if defined? @pattern_match
# ...
else
# ...
end
```

Here's some output of a build on travis:
https://travis-ci.org/rspec/rspec-core/jobs/71203492#L4498

**Comment by waterlink** [comment]
Sounds good to me. And actually we can just initialize this instance variable to `false` in `initialize` method to make warning go away.

**Comment by waterlink** [comment]
Additionally, we can enable `config.warnings = true` to potentially catch these during development.

**Comment by waterlink** [comment]
@dg-ratiodata Are you up to making pull request?

**Comment by alex-fedorov** [comment]
I see, you have more warnings to fix, I can tackle this one, don't bother
:-)

**Comment by dg-ratiodata** [comment]
Thanks a lot ;-)

**Comment by dg-ratiodata** [comment]
Some strange ones too...

**Comment by dg-ratiodata** [comment]
#179 done.

**Comment by alex-fedorov** [comment]
@egonSchiele I have pushed bump up for `0.10.1`. Can you release it to rubygems?

**Comment by egonSchiele** [comment]
Yup!

**Comment by egonSchiele** [comment]
Done.

**Comment by dg-ratiodata** [comment]
@myronmarston The first issue / warning is fixed...

**Comment by waterlink** [comment]
Closing this, since it looks like solved. Comment here if there are still problems, will re-open.
