### ISSUE TITLE
Number groups builtin contracts.

### ISSUE THREAD

**Issue by sfcgeorge** [egonSchiele/contracts.ruby#204]
Unfortunately there is no mathematical consensus on what a Natural number is. It's either includes zero or does not depending who you ask. In one notation a + is used to disambiguate (my lecturer did this):

N = N^0 = N_0 = { 0, 1, 2, 3, ... }
N* = N+ = N_1 = N>0 = { 1, 2, 3, ... }

This is basically what we are doing with the `Nat` builtin contract. I would like to add a contract that doesn't include zero for completeness, so if we stick to the current definition of Nat then the contract to be added might be `NatP` for "Natural Positive".

There is an alternate notation I have seen that flips it around and uses W for the zero inclusive set for "Whole Numbers":

W = { 0, 1, 2, 3, ... }
N = { 1, 2, 3, ... }

This notation seems nonstandard though fairly widespread still. It would mean we'd have to change the definition of `Nat` then add `Whole` that replaced the old Nat.

We're also missing an `Int` contract. If we have `Num` as a shorthand for Numeric then we should have `Int` as a shorthand for `Integer`.

What do you think? I could open a pull request once we've decided.

**Comment by nixpulvis** [comment]
Within the context of computing I *very* rarely find myself wanting a definition of natural numbers to not include 0. Ruby has 0 indexed arrays, and such.

**Comment by sfcgeorge** [comment]
But programmers usually code things for the real world. It would be useful for:

* Shapes. You can't have a zero sided shape. 
* Quality, e.g. image quality 1-10.
* Preventing divide by zero.
* Quantities, how many of something in shopping basket, 1+

And lots more. In the real world, zero is often unwanted.

**Comment by nixpulvis** [comment]
Just for the sake of argument.

- Shapes, most drawing libraries I've used allow 0 sized objects.
- Quality, `(1-10)` is a range, not the set of natural numbers.
- Preventing divide by zero: This is a useful mathematical property, and probably the main use of this feature. I'd argue a `NonZero` contract or something akin to that might be a better solution.
- Quantities, why can't you have nothing in the basket?

**Comment by sfcgeorge** [comment]
* Why on earth would you want a zero sided shape? Though really 3 is the minimum sides that makes sense unless you're okay with open shapes. I suppose zero could be a node.
* True.
* `NonZero` is less consistent. I think it would be nice having all the number groups, which means adding `NatP` and `Int`.
* Not items in the basket, quantity of a particular item. Your basket wouldn't contain every item in the store with quantity set to zero, it would have only the items you want with a quantity of 1+.

**Comment by nixpulvis** [comment]
I just feel like the use case for `NatP` isn't common enough to include it as a builtin. Some people will want it, but in general I wouldn't use it.

**Comment by gsinclair** [comment]
I think it's worth including. Just put some thought into the name. I think `NatPos` might be best, in that an unseasoned person reading the code would almost certainly understand it straight away.

I'm pretty sure I've had one or two contracts like `And[Nat, -> (n) { n > 0 }]` in the past.

**Comment by nixpulvis** [comment]
@gsinclair I'd just write my own contract in that case.

```ruby
NatP = -> (n) { n && n.is_a?(Integer) && n >= 0 }
```

Small addition for the less common use cases.

**Comment by egonSchiele** [comment]
There's a bigger issue here: do we want to keep the set of builtin contracts small or not? I personally don't see a reason to keep it small, and I'm happy to include both `NatP` and `Int`. I like it when libraries have "batteries included", it reduces the number of utility functions/types I need to keep copying around.

**Comment by waterlink** [comment]
:+1: for this contract from my side /cc @egonSchiele @sfcgeorge

**Comment by PikachuEXE** [comment]
@egonSchiele 
If the built-in contracts become very large in the future
Maybe you can consider putting them into groups (modules)
And add a special module that includes them all

But how to group them is another question
