### ISSUE TITLE
Is it possible to customize contract error messages?

### ISSUE THREAD

**Issue by fblundun** [egonSchiele/contracts.ruby#205]
Our application is configured using a nested hash parsed from a YAML file. We use a hash contract to validate that the file contains the correct fields and that they are of the correct type.

When the file is incorrectly configured, the error message from the contract contains the string representations of the contract and the malformed hash. But these are quite large, which makes it hard to see exactly which field was to blame. Is there a way for us to modify the contract or monkey patch the library so that the error message explicitly states which field of the hash was incorrect?

[This](https://github.com/snowplow/snowplow/blob/2f15490d5348b732bb7488c6a4eea4dc8f10acc5/3-enrich/emr-etl-runner/lib/snowplow-emr-etl-runner/contracts.rb#L86) is the hash contract in question.

**Comment by egonSchiele** [comment]
Hi @fblundun,
This sounds useful, I'd like to make it the default behavior for contracts.ruby. The error message gets constructed here: https://github.com/egonSchiele/contracts.ruby/blob/master/lib/contracts.rb#L128

Right now it just calls `.inspect` on the actual data. I would change this so if the contract is a hash, and a hash was passed in, we try to print out the differences in the two hashes. Would you feel comfortable making this change yourself? We can discuss the best approach and I can point you to the relevant files to modify.

**Comment by waterlink** [comment]
BTW, it is possible to override failure handler entirely with your own: https://github.com/egonSchiele/contracts.ruby/blob/master/TUTORIAL.md#failure-callbacks

**Comment by waterlink** [comment]
@fblundun Any news on this one? Were the `Contract.override_failure_callback` enough for you needs?

**Comment by fblundun** [comment]
Sorry for the very late reply. I haven't tried overriding the failure callback - I we will probably end up writing a JSON schema for our configuration file and using that for validation, since JSON schema validation provides a sufficiently readable report on what went wrong.

**Comment by waterlink** [comment]
@fblundun Yeah, I can only agree: JSON schema in this case would be better!
