### ISSUE TITLE
reek warnings

### ISSUE THREAD

**Issue by mcandre** [egonSchiele/contracts.ruby#21]
I took a look with the popular Ruby linter [reek](https://github.com/troessner/reek) to examine potential sources of bugs. There actually aren't that many :)

    $ reek -q lib
    lib/builtin_contracts.rb -- 11 warnings:
    Contracts::::Hash has no descriptive comment (IrresponsibleModule)
    Contracts::::Hash#test_data contains iterators nested 2 deep (NestedIterators)
    Contracts::::Hash#test_data has approx 12 statements (TooManyStatements)
    Contracts::::String has no descriptive comment (IrresponsibleModule)
    Contracts::Any#self.valid? has unused parameter 'val' (UnusedParameters)
    Contracts::Args#test_data calls Testable.test_data(@contract) 3 times (DuplicateMethodCall)
    Contracts::ArrayOf#test_data calls Testable.test_data(@contract) 3 times (DuplicateMethodCall)
    Contracts::ArrayOf#valid? refers to vals more than self (FeatureEnvy)
    Contracts::Bool has no descriptive comment (IrresponsibleModule)
    Contracts::Maybe#initialize refers to vals more than self (FeatureEnvy)
    Contracts::None#self.valid? has unused parameter 'val' (UnusedParameters)
    lib/contracts.rb -- 24 warnings:
    Contract#call_with calls _args[i] twice (DuplicateMethodCall)
    Contract#call_with has approx 13 statements (TooManyStatements)
    Contract#call_with has the variable name 'i' (UncommunicativeVariableName)
    Contract#call_with has the variable name 'j' (UncommunicativeVariableName)
    Contract#initialize calls contracts[-1] 3 times (DuplicateMethodCall)
    Contract#pretty_contract doesn't depend on instance state (UtilityFunction)
    Contract#pretty_contract has the parameter name 'c' (UncommunicativeParameterName)
    Contract#pretty_contract refers to c more than self (FeatureEnvy)
    Contract#self.failure_msg calls data[:contract] 4 times (DuplicateMethodCall)
    Contract#self.failure_msg calls data[:contract].to_s twice (DuplicateMethodCall)
    Contract#self.failure_msg calls data[:method] 7 times (DuplicateMethodCall)
    Contract#self.failure_msg has approx 9 statements (TooManyStatements)
    Contract#self.make_validator calls lambda 7 times (DuplicateMethodCall)
    Contract#self.make_validator contains iterators nested 2 deep (NestedIterators)
    Contract#self.make_validator has approx 13 statements (TooManyStatements)
    Contract#self.make_validator has the variable name 'k' (UncommunicativeVariableName)
    Contract#to_s has the variable name 'c' (UncommunicativeVariableName)
    ContractError has no descriptive comment (IrresponsibleModule)
    Contracts#self.common calls contracts.nil? twice (DuplicateMethodCall)
    Contracts#self.common calls self.class 3 times (DuplicateMethodCall)
    Contracts#self.common performs a nil-check. (NilCheck)
    Contracts#self.common#Contract has the name 'Contract' (UncommunicativeMethodName)
    Contracts#self.common#functype calls self.class twice (DuplicateMethodCall)
    Contracts#self.common#functype performs a nil-check. (NilCheck)
    lib/decorators.rb -- 5 warnings:
    Decorator has no descriptive comment (IrresponsibleModule)
    Decorator#initialize has unused parameter 'klass' (UnusedParameters)
    Decorator#self.inherited has the variable name 'm' (UncommunicativeVariableName)
    MethodDecorators#common_method_added has approx 13 statements (TooManyStatements)
    MethodDecorators#common_method_added is controlled by argument is_class_method (ControlParameter)
    lib/testable.rb -- 5 warnings:
    Contracts::Testable has no descriptive comment (IrresponsibleModule)
    Contracts::Testable#self.check calls meth.name twice (DuplicateMethodCall)
    Contracts::Testable#self.check has approx 15 statements (TooManyStatements)
    Contracts::Testable#self.check_all has the variable name 'o' (UncommunicativeVariableName)
    Contracts::Testable#self.product has the variable name 'x' (UncommunicativeVariableName)

Would you consider writing a `.reek` to ignore some of these warnings, and refactor out the others?

**Comment by sfcgeorge** [comment]
I suggest [Rubocop](https://github.com/bbatsov/rubocop) instead as it seems more popular now.

**Comment by egonSchiele** [comment]
Marking as fixed.
