### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by rap-kasta** [egonSchiele/contracts.ruby#220]
Please, update gem version according to [Semantic Versioning](http://semver.org) with each valuable change in code. This way we can include contracts with bug fixes and new features in gemspec files (it is impossible to configure gemspec to use git).

**Comment by waterlink** [comment]
@rap-kasta Hi, thanks for creating an issue!

I was wondering why so many commits are not released (according to Github releases page), but after looking a bit, I understood, that `v0.12.0` was released "recently" to RubyGems, but there is no tag in Git and Github. So I tagged the released commit and it is now available on Github too.

Additionally I have created a PR to bump up version to `v0.13.0` #221. @egonSchiele most probably, will release it to rubygems soon.

Cheers
