### ISSUE TITLE
Undefined variable in a lambda causes a segmentation fault

### ISSUE THREAD

**Issue by max11D** [egonSchiele/contracts.ruby#225]
It seems I made a typo in a contract and broke Rails.

```
Contract KeywordArgs[
		payment_method: Or[*Cart::PAYMENT_METHODS],
		country: lambda { |x| Duty.get_supported_duty_countries.keys.include?(key) },
		coupon: Optional[Or[Coupon, String, nil]]
	] => Numeric
def duty(payment_method:, country:, coupon: nil)
	# ...
end
```

Note that the contract on the "country" variable uses a "key" variable that isn't defined. While this is definitely my fault, I figure it probably shouldn't be causing a segmentation fault. I can attach the resulting dump if the issue isn't easily reproduceable. Doing the same in a lambda outside the contract fails gracefully.

Duty.get_supported_duty_countries returns a hash.

**Comment by egonSchiele** [comment]
Hey @max11D ,

I came up with this standalone snippet similar to your code:

```ruby
require "contracts"
include Contracts

Contract KeywordArgs[bar: lambda { |x| keys.include?(x) }] => Any
def foo(bar:)
  p bar
end

foo(bar: 1)
```

This throws an error like I would expect:

```
test.rb:4:in `block in <main>': undefined local variable or method `keys' for main:Object (NameError)
```

contracts.ruby is a pure Ruby gem, so I don't think this segfault is coming from here. It's more likely related to some other library you are using (maybe Rails) that has C extensions.

**Comment by egonSchiele** [comment]
I'm going to close this issue, please re-open if it turns out to be contracts after all.
