### ISSUE TITLE
Gem does not work

### ISSUE THREAD

**Issue by jph** [egonSchiele/contracts.ruby#226]
Hello! Not sure what's going on here! The gem is 'required' fine, but doesn't seem to work. This is an example from your documentation/tutorial.

```ruby
» cat script.rb
require 'contracts'

Contract Contracts::Num, Contracts::Num => Contracts::Num
def add(a, b)
  a + b
end

» ruby script.rb
script.rb:3:in `<main>': undefined method `Contract' for main:Object (NoMethodError)
```

```bash
$ ruby -v
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin15.0]
```

**Comment by egonSchiele** [comment]
James, it is not enough to require the library, you also need to add an `include` statement:

    include Contracts::Core

**Comment by jph** [comment]
Thanks, I can confirm that my script is now operational.

Your README and tutorial are unclear and do not include the line you have provided to me in your reply. From what I can tell there is no mention of this throughout the whole tutorial.

Thank you for your quick reply. This gem is very useful to me. :)

**Comment by waterlink** [comment]
@jph It is mentioned in the second example in the tutorial:

```ruby
require 'contracts'

class Math
  include Contracts::Core           # <<<<<==== This line

  Contract Contracts::Num, Contracts::Num => Contracts::Num
  def self.add(a, b)
    a + b
  end
end

puts Math.add(1, "foo")
```

**Comment by waterlink** [comment]
@jph Second point: you are not supposed to use contracts in global scope. It might not work as expected and starting from `1.0` will not be allowed at all.

**Comment by jph** [comment]
@waterlink thanks for the clarification, I did not realise this.
