### ISSUE TITLE
Strict Hash?

### ISSUE THREAD

**Issue by cbrwizard** [egonSchiele/contracts.ruby#235]
Hey, I've just started using this gem and I have noticed that when writing a contract for a hash 'You don't need to put a contract on every key'.
That is the contrary to what I need. I would like to define a strict schema of hash data and if a hash with additional keys is used, there should be a failure.
Is there a way to do that easily with this gem? Thanks!

**Comment by waterlink** [comment]
Sounds like you want to have a custom contract. Here is how you create one:

```ruby
class ExactlyHash
  def initialize(hash)
    @hash = hash
  end

  def valid?(arg)
    hash.all? do |key, contract|
      arg.has_key?(key) && Contract.valid?(arg[key], contract)
  end
end
```

And use it as `Contract ExactlyHash.new({ ... })`

**Comment by waterlink** [comment]
Sorry if code might not work, I am from the phone.

**Comment by cbrwizard** [comment]
@waterlink thank you for the code! It didn't work but I was able to quickly fix it based on your work.
Want me to add a pull request and add this Contract to the repo? Someone else might need this as well.

**Comment by egonSchiele** [comment]
Please do @cbrwizard ! Add it to this file:
https://github.com/egonSchiele/contracts.ruby/blob/master/lib/contracts/builtin_contracts.rb

Have your class inherit `CallableClass`:
https://github.com/egonSchiele/contracts.ruby/blob/master/lib/contracts/builtin_contracts.rb#L87

That way you can use it as `StrictHash[...]` instead of `StrictHash.new(...)`.

**Comment by cbrwizard** [comment]
Hey @egonSchiele I do not mean to push you or anything, but I'm just curious: is there a time estimate when StrictHash is going to be in the gem? I might need it in production soon =] I have tried to tell bundler to take code from github but for some reason it didn't download the last version. I am more a JS person than Ruby so sorry if I made a mistake here.

**Comment by egonSchiele** [comment]
@cbrwizard I just pushed it to rubygems! Look for v0.14.0.

**Comment by cbrwizard** [comment]
@egonSchiele awesome! It works in my project. I guess we can close this issue now
