### ISSUE TITLE
[chore] Add git tag v0.16.0 for 98cad257

### ISSUE THREAD

**Issue by olleolleolle** [egonSchiele/contracts.ruby#266]
Hi!

There's no Git tag for the v0.16.0.

It was released from 98cad25741b2dc0462229a417e3c6660e563cd84.

**Comment by olleolleolle** [comment]
I noted this issue when working on #267.

**Comment by egonSchiele** [comment]
Done!

**Comment by olleolleolle** [comment]
_Thank you!_
