### ISSUE TITLE
GitHub release missing for v0.17.0

### ISSUE THREAD

**Issue by mscwilson** [egonSchiele/contracts.ruby#297]
Hi, it looks like you forgot to create a Github release for the latest version! It's on [RubyGems](https://rubygems.org/gems/contracts/versions/0.17) only.

Thanks for all your work.

**Comment by PikachuEXE** [comment]
Thanks for reminding us!
Just created [a tag for 0.17](https://github.com/egonSchiele/contracts.ruby/releases/tag/v0.17)
(Yes I do notice that it should be `0.17.0` but what's done is done 😓 )

**Comment by mscwilson** [comment]
Haha, thanks!
