### ISSUE TITLE
Contract error when mixing positional and keyword arguments with defaults

### ISSUE THREAD

**Issue by vlad-pisanov** [egonSchiele/contracts.ruby#304]
I'm having trouble defining a contract for a method that takes two optional arguments -- a positional one and a keyword one. Consider:

```ruby
class C
  include Contracts

  Contract String, KeywordArgs[b: Optional[String]] => Any
  def foo(a = 'a', b: 'b')
    p [a, b]
  end
end

c = C.new
c.foo('a', b: 'b') # Works ✔️
c.foo('a')         # Works ✔️
c.foo(b: 'b')      # Contract error ❌
c.foo              # Contract error ❌
```

The stack trace is
```
Contract violation for argument 1 of 1: (ParamContractError)
        Expected: String,
        Actual: {:b=>"b"}
        Value guarded in: C::foo
        With Contract: String, KeywordArgs => Any
        At: c.rb:9

      fail data[:contracts].failure_exception.new(failure_msg(data), data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /Users/main/.gem/ruby/3.3.2/gems/contracts-0.17/lib/contracts.rb:197:in `failure_callback'
        from /Users/main/.gem/ruby/3.3.2/gems/contracts-0.17/lib/contracts/method_handler.rb:144:in `block in redefine_method'
```

It seems Contracts wants me to provide the positional argument even if a default is specified in the method signature? 🤔

**Comment by PikachuEXE** [comment]
I don't even know how it handles positional optional arguments
I see nothing from https://egonschiele.github.io/contracts.ruby/
Have you used contract on methods with positional optional arguments only?

**Comment by vlad-pisanov** [comment]
It is indeed not documented, but it works as expected when only positional arguments are used:
```ruby
class C
  include Contracts

  Contract String, String => Any
  def goo(a = 'a', b = 'b')
    p [a, b]
  end
end

c = C.new
c.goo           # Works ✔️
c.goo('a')      # Works ✔️
c.goo('a', 'b') # Works ✔️
```

The issue seems to be in `KeywordArgs`, because if I replace the original example with `Any`, everything works again:
```ruby
class C
  include Contracts

  Contract String, Any => Any
  def hoo(a = 'a', b: 'b')
    p [a, b]
  end
end

c = C.new
c.hoo('a', b: 'b') # Works ✔️
c.hoo('a')         # Works ✔️
c.hoo(b: 'b')      # Works ✔️
c.hoo              # Works ✔️
```

**Comment by PikachuEXE** [comment]
I think it's a deeper issue of lacking a contract for **optional** positional argument
From my limited understand it works like this
1. Declare contracts, e.g. Contract contract_at_pos_1, contract_at_pos_2, contract_keyword_args
2. When called, check against contracts **according to position**: arg1 => contract_at_pos_1, arg2 => contract_at_pos_2...

It's fine for methods with optional arguments only coz it works like:
Contracts declared: contract_at_pos_1, contract_at_pos_2
When some arguments not passed, it checks like: arg1 => contract_at_pos_1, no arg2 = no check

But if **optional** positional argument is mixed with keyword arguments
Contracts declared: contract_at_pos_1, contract_keyword_args
It checks like: keyword_args => contract_at_pos_1

I am guessing from
https://github.com/egonSchiele/contracts.ruby/blob/v0.17/lib/contracts/call_with.rb#L51-L81

**Comment by PikachuEXE** [comment]
Please check https://github.com/egonSchiele/contracts.ruby/pull/305 and see if you want to add more examples to ensure I don't break anything
Use it in your app for a while to ensure nothing breaks

**Comment by PikachuEXE** [comment]
I won't merge https://github.com/egonSchiele/contracts.ruby/pull/305 until some has tested it~

**Comment by vlad-pisanov** [comment]
@PikachuEXE everything looks good! 🚀 No issues in our 4K+ file repo.

**Comment by PikachuEXE** [comment]
Let me release it next week if no other PR blocking

**Comment by PikachuEXE** [comment]
I forgot I don't have release right in this gem
@egonSchiele Please release a new version `0.17.1` thx
Changes: https://github.com/egonSchiele/contracts.ruby/compare/v0.17...master

**Comment by egonSchiele** [comment]
I’m traveling, give me a few daysOn Sep 22, 2024, at 8:38 PM, PikachuEXE ***@***.***> wrote:﻿
I forgot I don't have release right in this gem
@egonSchiele Please release a new version 0.17.1 thx
Changes: v0.17...master

**Comment by egonSchiele** [comment]
done

**Comment by PikachuEXE** [comment]
Tag on wrong commit 😅 
![image](https://github.com/user-attachments/assets/4f12621f-d0b1-423f-ad40-2aae22574343)
