### ISSUE TITLE
Can't override failure_callback *and* over method overloading

### ISSUE THREAD

**Issue by egonSchiele** [egonSchiele/contracts.ruby#31]
The implementation of method overloading currently relies on catching the `ContractError` that is thrown by the default `failure_callback`. If you override `failure_callback` and it doesn't throw a `ContractError` anymore, method overloading won't work...it will just try the first option and fail if it's not correct.

**Comment by waterlink** [comment]
Now this one can be tackled, since we can understand if it is a pattern matching or not inside the `Contract` class code.
