### ISSUE TITLE
Add YARD support

### ISSUE THREAD

**Issue by yonkeltron** [egonSchiele/contracts.ruby#32]
While I love writing contracts in my code, I find that I must duplicate my type annotations when documenting that same code. I use [YARD](http://yardoc.org/) for generating documentation which, allegedly, [supports special DSLs in Ruby](http://yardoc.org/guides/extending-yard/writing-handlers.html).

It would really rock if contracts.ruby shipped with YARD support to make documentation easier! Happy to help beta test this feature and contribute however I can.

Thanks!

**Comment by iainbeeston** [comment]
Is there any update on this? It would be really cool to have. (Or indeed any way of defining types in comments, so I don't have to mark Contracts as a runtime dependency)

**Comment by iainbeeston** [comment]
Sorry, must have had a crazy moment there - obviously you'd need to load contracts as a runtime dependency. But it would still be nice to be able to define type signatures in comments.

**Comment by alex-fedorov** [comment]
Hi @iainbeeston. Why do you want to define type signatures in comments? While you can define them in code. Example:

```ruby
Contract Rack::Request => Rack::Response
def handle(env)
  # ...
end
```

**Comment by sfcgeorge** [comment]
This is actually the thing I wanted in the first place, being able to define attribute validations in terse code and have them automatically documented without manual duplication. So I plan on having a go at finishing off YARD integration, hopefully it's possible. Any other thoughts on it?

**Comment by iainbeeston** [comment]
@alex-fedorov No, you're probably right. Comments don't make much sense when type checking must be done at runtime. Generating YARD comments would be great though.

**Comment by iainbeeston** [comment]
I was imagining that type checking could be performed statically, in a similar way to Facebook flow for javascript, but I think that's not what contracts.ruby is for.

**Comment by sfcgeorge** [comment]
Yeah Contracts hooks in at run time, something else would need to be written from scratch for static analysis. Might be another useful tool to have in your arsenal but for different purposes.

Check out the multiple dispatch pattern matching of Contracts, it's really cool and a great justification of doing it at run time.

I have made progress already on integrating with YARD! I'm very excited. I just have to flesh it out, add some tests and then hopefully I can send a tentative pull request in a few days. Just wanted you to know I'm working on it and it's going well :)

**Comment by sfcgeorge** [comment]
I have initial YARD support working in my fork, pull #114, perhaps some of you would like to try it out. It's described in the pull request.

**Comment by sfcgeorge** [comment]
I have wrapped this as a YARD plugin in a beta gem. It's now easy to add YARD doc support to a project using Contracts. This issue can probably be closed now. Issues with the gem can be posted directly on that repo. https://github.com/sfcgeorge/yard-contracts

**Comment by sfcgeorge** [comment]
The `yard-contracts` gem is now tested and pushed to Rubygems. Enjoy :)

**Comment by waterlink** [comment]
What about this PR then #114 ? Does `yard-contracts` works if you are not on the master of `contracts` ? @sfcgeorge I thought you wanted to have some changes to `InspectWrapper` class..

**Comment by egonSchiele** [comment]
I can push a new version of contracts, lots of changes have been made.

**Comment by sfcgeorge** [comment]
As noted in PR #114 some changes to Contracts (InspectWrapper) are desirable for the yard-contracts gem. However the current Rubygems version of yard-contracts works with the current version of Contracts, no master needed, by simply duplicating and overriding InspectWrapper for now.
