### ISSUE TITLE
Feature: Append contract type signature to rdoc output

### ISSUE THREAD

**Issue by apennebaker** [egonSchiele/contracts.ruby#34]
Ruby Contracts would be even more amazing if they automatically informed rdoc output. People might even scratch their heads and wonder, is this really RDoc, or Javadoc?

**Comment by NobbZ** [comment]
Has any progress been made on this? I use yard for documentation of my project and want to use `contracts` now too. So it would be really helpfull if I don't need to repeat information in the `Contract`-line and the yard-block

**Comment by waterlink** [comment]
@NobbZ here you go: https://github.com/sfcgeorge/yard-contracts I am not sure, but you may need to use latest `contracts` master branch (but I think latest released version should work).

**Comment by NobbZ** [comment]
OK, found it and it seems to work. Thank you!

**Comment by egonSchiele** [comment]
I'm going to close this issue for now. @apennebaker please feel free to send over a PR on this if you still need it!
