### ISSUE TITLE
`rspec --order random` for this gem makes a lot of failures, when `rspec` succeeds

### ISSUE THREAD

**Issue by alex-fedorov** [egonSchiele/contracts.ruby#54]
So I assume some specs change some global state, or monkey patch something, and everything called after ends with error `SystemStackError: stack level too deep`. Or worse: some functionality does affect some sort of global state.

Any ideas what could be responsible for that ?

**Comment by egonSchiele** [comment]
Nice catch! I do have global state, will fix.

**Comment by waterlink** [comment]
Tackled this problem (actually both of two problems that are related to this) in #58
