### ISSUE TITLE
Feature proposal: Invariants

### ISSUE THREAD

**Issue by alex-fedorov** [egonSchiele/contracts.ruby#56]
So when I read some stuff on DbC (Design by Contract) and particularly a bit about Eiffel (the language, that is known for implementing DbC on language level), I seen besides defensive statements (Contracts) such thing as an invariant.

Basically it is yet another condition which should always be true on the object of the class, otherwise it blows up with invariant violation error. It is checked probably before and after method call on this object succeeded.

Do you see a need for this in this gem?

I would think it will look something like:

```ruby
# very silly example, since we already have a proper Date object out there :)
class MyBirthday < Struct.new(:day, :month)
  Invariant { 1 <= day && day <= 31 }   # or use ranges here
  Invariant { 1 <= month && month <= 12 }

  # ... methods goes here ...
end
```

And the violation could look like that

```
./invariant.rb:38:in `failure_callback': Invariant violation: (RuntimeError)
    Expected: { 1 <= day && day <= 31 },
    Actual: 32
    Value guarded in: #<MyBirthday:0x000001021a40f8>
    At: main.rb:6 
    ...stack trace...
```

I basically already have a gist of this gem, and can implement it if you want it in.

@egonSchiele, WDYT?

**Comment by egonSchiele** [comment]
Yeah, I think that's a great idea. Please send a PR!
