### ISSUE TITLE
NO_CONTRACTS does not remove time overhead

### ISSUE THREAD

**Issue by waterlink** [egonSchiele/contracts.ruby#60]
If I run benchmarks, I see that with NO_CONTRACTS=1 they are slightly faster, but still have a huge overhead. This commit shows how this can be fixed: https://github.com/waterlink/contracts.ruby/commit/557e66f571d6051fe76f763f461cee0a0819af1f

**Comment by egonSchiele** [comment]
Take a look, now both benchmarks are equally fast for me:

```
                                     user     system      total        real
testing add                      0.360000   0.000000   0.360000 (  0.361024)
testing contracts add            0.370000   0.000000   0.370000 (  0.368626)
```

**Comment by waterlink** [comment]
Works for me too on master!
