### ISSUE TITLE
*args, &block

### ISSUE THREAD

**Issue by mushishi78** [egonSchiele/contracts.ruby#65]
Hi, great gem!

Unless I've missed something, it seems that for methods with both a splat and a block, the block gets put in with the splat for the contract checks. This is the only way I've found to get it too work:

``` ruby
Contract Args[Or[Symbol, Proc]] => Any
def method(*args, &b)
```

Which allows procs to be put in any where in the splat. Is there a better way of doing this? If so, can it be added as an example in the tutorial?

Thanks.

**Comment by waterlink** [comment]
@mushishi78 Thx for reporting, bug confirmed, I will look into this.

**Comment by waterlink** [comment]
Ideally, it should be like this:

```ruby
Contract Args[Symbol], Proc => Any
def method(*args, &b)
```
