### ISSUE TITLE
`self` in inherited singleton methods gives parent class

### ISSUE THREAD

**Issue by mushishi78** [egonSchiele/contracts.ruby#66]
If I put a contract on a singleton method, when inherited self refers to it's parent class, rather then itself.
Here's a rough spec if it helps clarify what I mean:

``` ruby
class A
  include Contracts

  def self.my_normal_method
    self
  end

  Contract Any => Any
  def self.my_contracted_method
    self
  end
end

class B < A
end

describe B do
  it do
    expect(B.my_normal_method).to eq(B)
  end

  it do
    expect(B.my_contracted_method).to eq(B)
  end
end
```

The second test would fail.

**Comment by waterlink** [comment]
@mushishi78 thx for reporting, bug confirmed, I will look into this.

**Comment by mushishi78** [comment]
Thanks for the quick response!
