### ISSUE TITLE
Should allow contracts on blocks

### ISSUE THREAD

**Issue by egonSchiele** [egonSchiele/contracts.ruby#72]
Issue for my comment in pull #68:

Currently, I can't add a contract on a block like this:

```ruby
Contract Num, Func[Num => Num] => nil
def double x, &blk
  blk.call(x)
  nil
end
```

**Comment by waterlink** [comment]
Now it poses some serious problem:

```ruby
Contract Args[Num], Func[Num => Num] => nil
def double *args, &blk
  # ...
end
```

- it definitely should accept `double(1, 2, 3, ..., n) { |x| x * x + 1 }` !
- should it accept `double(1, 2, 3, ..., n, Proc.new { |x| x * x + 1 })` ? Technically block wasn't given, but we haven't actually required block anywhere, we just stated that last argument is `Func[Num => Num]`.

**Comment by waterlink** [comment]
But since it is an argument after `Args[Num]` which is possible only for `&blk`-type argument, then it is clear.

**Comment by kliuless** [comment]
The feature is very useful. Can we mention it in the tutorial?

**Comment by egonSchiele** [comment]
What about the `Contracts On Functions` section?
http://egonschiele.github.io/contracts.ruby/

**Comment by kliuless** [comment]
Yes, it makes the most sense to be in that section. I'm thinking a short note at the end of the section would be enough, right before "NOTE: This is not valid" (btw, I just noticed that note's example uses `&func`).

Something like:

> The above examples showed a method accepting a `Proc` as the last argument, but the same contract works on methods that accept a block:

> ```ruby
def map(arr, &block)
```

**Comment by waterlink** [comment]
In ruby `Proc` is the class of block, ie:

```ruby
def type_of_what_you_pass_in(&blk)
  blk.class
end

type_of_what_you_pass_in do
  # ...
end
```

Will return: `Proc`

**Comment by waterlink** [comment]
Ah, I see, such small example will still be nice to have. @kliuless are you up to making a PR ? :)

**Comment by kliuless** [comment]
Sure, hopefully I'll have some time tomorrow.
Also, note that `&blk` isn't strictly needed in the method signature, in which case you'd call the block using `yield`. I'm not going to mention this in the PR, unless you think it's needed.
