### ISSUE TITLE
Code highlighting in tutorial

### ISSUE THREAD

**Issue by alex-fedorov** [egonSchiele/contracts.ruby#76]
I can't see any, do you have any leads why can it be gone?

**Comment by egonSchiele** [comment]
Weird, I don't see it either. Let me see if I can contact github.

**Comment by egonSchiele** [comment]
I haven't heard anything about this and that repo has plenty of ignored issues. Maybe we should move away from a hosted theme and make our own theme.

**Comment by egonSchiele** [comment]
Github finally fixed it.
http://egonschiele.github.io/contracts.ruby/
