### ISSUE TITLE
Tutorial: overloading == pattern matching

### ISSUE THREAD

**Issue by kliuless** [egonSchiele/contracts.ruby#79]
I don't know if you realize this, but your library implements [pattern matching](http://en.wikipedia.org/wiki/Pattern_matching). One thing "missing" is that you can't automatically pass the matched values as local variables to the method body (but I'm not even sure if this is essential to PM).

Example: I can specify arbitrary nesting

    Contract ({a: Num, b: [[String]]}) => String
    def add h
      h[:a].to_s + h[:b][0][0]
    end
    add(a: 2, b: [['4']])

The tutorial calls this "overloading", but I think it is also useful to use the name "pattern matching" so Googling for "pattern matching in ruby" would lead here :)

**Comment by waterlink** [comment]
I know, I am calling it pattern matching too. So might as well fix tutorial to call it the same. Do you want to take a stub on it?

**Comment by kliuless** [comment]
Sorry, not sure what you're asking me to do?

**Comment by waterlink** [comment]
Sorry, it was a bit of jargon.

Do you want to fix the documentation in Tutorial and create a PR?

If you are not, then I will just do it a bit later.

**Comment by kliuless** [comment]
Ok, I'll create a PR.
I'm not going to remove the current example, I will only add more so people can see both simple and complex examples.

**Comment by waterlink** [comment]
:+1:

**Comment by waterlink** [comment]
By the way @kliuless don't hesitate to ask any questions if you have any

**Comment by kliuless** [comment]
Do you think it was inaccurate for me to say "rather than using conditionals"? I really meant conditional branching statements like if/else. (I'm sort of obsessive about precision when writing docs.)
