### ISSUE TITLE
Add Blame

### ISSUE THREAD

**Issue by disnet** [egonSchiele/contracts.ruby#8]
Great work! Just wanted to point out that it looks like contracts.ruby doesn't correctly track blame for higher-order functions. This is one of the more non-obvious pices of a contract system the people often miss but basically the idea is that if you just rely on the stack trace you'll wind up blaming the wrong code.

For example,

    module A
      Contract ArrayOf[Num], Func[Num => Num] => ArrayOf[Num]
      def map(arr, func)
        ...
      end
    end

    module B
      def run()
        map([1,2,3], lambda { |x| "bad" }
      end
    end

Just relying on the stack trace will blame module A even though B violated the contract by providing a bad function. There's a seminal paper [1] on the subject if you're interested.

[1] http://www.eecs.northwestern.edu/~robby/pubs/papers/ho-contracts-icfp2002.pdf

**Comment by waterlink** [comment]
Would it be enough to blame higher order functions creation location only when return part of `Func` contract fails. I don't see now example, where you could blame wrong module, if the violation is in its arguments.

**Comment by egonSchiele** [comment]
I'm wondering what needs to change for the error message. Take this example: https://gist.github.com/egonSchiele/eae82ff260620ebf0a8c

A bad function gets passed from B -> C -> A.

The error message looks like this:

        Expected: Num,
        Actual: "bad"
        Value guarded in: A::Proc
        With Contract: Num => Num
        At: test.rb:17

Here's line 17:

```ruby
C.indirect_map([1,2,3], lambda { |x| "bad" })
```

So it tells you the line where the bad function was passed in. The contract that violated was for the function in class `A`.

That seems enough to me?

**Comment by waterlink** [comment]
Can we close this? It lacks activity, and I think current blame works just fine.

**Comment by egonSchiele** [comment]
Closed.
