### ISSUE TITLE
Constants not available in singleton class scope

### ISSUE THREAD

**Issue by kliuless** [egonSchiele/contracts.ruby#83]
Comments speak for themselves. However, if I use the `def self.size` syntax, the error goes away.

    class TestBug
      # If removed, I get this:
      #   "In order to use contracts in singleton class, please include Contracts module in original class"
      # Ok, no problem.
      include Contracts
    
      class << self
        # If removed, I get this:
        #   in `singleton class': uninitialized constant Class::ArrayOf
        # Seems pointless to include twice.
        include Contracts
    
        Contract ArrayOf[Any] => Integer
        def size(arr)
          arr.size
        end
      end
    end
    
    p TestBug.size([1,2,3])

**Comment by alex-fedorov** [comment]
Thx for reporting, it makes sense.

**Comment by alex-fedorov** [comment]
And the fix is pretty simple - automatically include Contracts in
Eigenclasses (singleton classes)
