### ISSUE TITLE
Tutorial: behavior of NO_CONTRACTS

### ISSUE THREAD

**Issue by kliuless** [egonSchiele/contracts.ruby#85]
It's not clear what actually is disabled when NO_CONTRACTS is set. Overloading still works, and it still raises contract-violation on a failed match. Non-overloaded methods don't raise though.

**Comment by waterlink** [comment]
With NO_CONTRACTS only pattern-matching contracts are defined. Normal `Contracts` doesn't even get defined. So with NO_CONTRACTS, for example in production, you can drop overhead of contracts on most methods, except pattern matching.

You can try to run benchmarks with and without option set, you will see a big difference :)

And yes, looks like tutorial needs updating on what is actually gets defined and what is not.

**Comment by waterlink** [comment]
@kliuless thx for noticing this!

**Comment by alex-fedorov** [comment]
To me looks like, this issue is fixed with 060f3ac

**Comment by egonSchiele** [comment]
Closing as fixed...let me know if this text isn't clear enough.

**Comment by kliuless** [comment]
Looks good to me. Thanks.
