### ISSUE TITLE
Best practice for lambda argument?

### ISSUE THREAD

**Issue by kliuless** [egonSchiele/contracts.ruby#88]
The tutorial mentions this construct for contracts on passed-in functions: `Func[Num => Num]`.
In one use case, I wanted to check that a function was passed, but didn't care about it's arg or return types, so I tried using `Func`. But the contract kept failing.

It seems that `Func` requires a nested contract. Either of these worked:
- `Func[Any => Any]`
- `Proc`

Is the best-practice to use `Proc`?
Also, if `Func` was designed to require a nested contract, maybe it should fail at the point of declaration if it's not given one.

**Comment by alex-fedorov** [comment]
Unless you want to pass around contracts of type `Func` ?

**Comment by alex-fedorov** [comment]
ie: `Func` - class, which will check if argument `.is_a(Func)` and `Func[Any => Any]` is an instance of `Func` class, which will check if argument is a higher order function and apply contract to it.

So I don't see why one could fail when using just `Func` it is a valid usage, though very rare one.

**Comment by alex-fedorov** [comment]
And if you want to just check for block being there or not, then `Proc` is good to go

**Comment by kliuless** [comment]
Yes, I see what you mean about passing instances of `Func` (I didn't realize what `Func` instances were until now). I guess the same thing applies to any `CallableClass` like `And` and `Or`. It seems like there should be a caution in the docs about using `Func` by itself.

In the other callables, it "feels" different when using them with a nested contract versus standalone. `Contract Or => ...` feels very different from `Contract Or[...] => ...`. The standalone form looks strange, so it's harder to accidentally use it when you mean the nested form. But it's very easy to think that `Func` acts like `Func[Any => Any]`. Just my opinion.

**Comment by waterlink** [comment]
@kliuless maybe you are right about that. I imagine contract `Func` to be able just to check that it is any function (either Proc or method). For that it needs to define `self.valid?(argument)`

**Comment by kliuless** [comment]
Well, I was only asking for a clarification in the docs, but I'm ok if the behavior changes too.

Since validating actual `Func` instances is rare, this can be done by using `Exactly[Func]`.

**Comment by egonSchiele** [comment]
I would rather leave this behavior as is and clarify the docs. I think making `Func` do double duty will make the built-in contracts inconsistent. Are you ok with that @kliuless ?

**Comment by kliuless** [comment]
I'm ok with leaving it as-is, with a clarifying doc.

Another thought:
`Func`'s behavior is consistent with how `And` works, but not intuitive based on its name. Maybe the `Func` name should be deprecated in favor of another name that suggests it needs a nested contract? I'm not sure what name would fit though.

**Comment by egonSchiele** [comment]
Take a look at this explanation. For the sake of backwards compatibility I don't want to rename `Func` unless necessary. But hopefully this explanation makes the usage clear.

**Comment by waterlink** [comment]
Looks pretty good to me

**Comment by kliuless** [comment]
Looks fine, thanks.

**Comment by waterlink** [comment]
Thanks for reporting this tutorial problem, @kliuless
